name: Varo
author: Nooby
authors: [Cuuky, Korne127, LeStegii, Almighty-Satan]
version: 69420
softdepend: [PlaceholderAPI, LabyModAPI, TelegramPlugin, PermissionsEx, LabyModAPI]
loadbefore: [CuukyFrameWork, JDA]
api-version: 1.13
main: de.cuuky.varo.Main
website: VaroPlugin.de